hashtable: main.cpp open_address_table.cpp open_address_table.h record.cpp record.h table_tests.cpp table_tests.h
	g++ -g -o hashtable main.cpp open_address_table.cpp open_address_table.h record.cpp record.h table_tests.cpp table_tests.h

clean:
	rm -rf hashtable debug core 
