bintree: main.c bst.c bst.h tree_tests.c tree_tests.h
	gcc -o bintree main.c bst.c bst.h tree_tests.c tree_tests.h

debug: main.c bst.c bst.h tree_tests.c tree_tests.h
	gcc -g -o debug main.c bst.c bst.h tree_tests.c tree_tests.h

clean:
	rm bintree debug core debug.txt


